---
# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: mdtopdf
version: 2
before:
  hooks:
    - git submodule update --remote  --init
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
    - go install github.com/cpuguy83/go-md2man@latest
    - go-md2man -in md2pdf.1.md -out md2pdf.1
    - gzip md2pdf.1

builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - darwin
      - freebsd
      - netbsd
      - android 
      - windows
    goarch:
      - amd64
      - arm64

    main: cmd/md2pdf/md2pdf.go
    id: md2pdf
    binary: md2pdf


archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  - package_name: mdtopdf
  - file_name_template: "{{ .ConventionalFileName }}"
    id: packages
    homepage: https://github.com/solworktech/md2pdf
    description: |-
      Markdown to PDF converter
      A CLI utility which, as the name implies, generates PDF from Markdown.
      Features: syntax highlighting (for code blocks),
      dark, light and custom themes,
      pagination control (using horizontal lines - useful for presentations),
      page Footer (consisting of author, title and page number),
      support of non-Latin charsets and multiple fonts
    maintainer: Jesse Portnoy <jesse@packman.io>
    license: MIT
    vendor: Solworktech
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./custom_themes
        dst: /usr/share/{{ .PackageName }}
        expand: true
        file_info:
          mode: 0755
      - src: ./highlight/syntax_files
        dst: /usr/share/{{ .PackageName }}/syntax_files
        expand: true
        file_info:
          mode: 0755
        type: "config|noreplace"
      - src: ./LICENSE
        dst: /usr/share/doc/{{ .PackageName }}/copyright
        expand: true
        file_info:
          mode: 0644
          # mtime: "{{ .CommitDate }}"
      - src: ./README.md
        dst: /usr/share/doc/{{ .PackageName }}/
        expand: true
        file_info:
          mode: 0644
      - src: ./md2pdf.1.gz
        dst: /usr/share/man/man1/
        expand: true
        file_info:
          mode: 0644
    formats:
      - deb
      - rpm
      - archlinux
# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
